"""Add is_ignored to UserQuestionMastery

Revision ID: 1d4704bd1918
Revises: d53f6d21cd04
Create Date: 2026-05-31 16:15:36.818898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4704bd1918'
down_revision: Union[str, Sequence[str], None] = 'd53f6d21cd04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # =========================================================================
    # ECOSYSTEM MIGRATION GUIDELINE:
    # Always write IDEMPOTENT migrations. Check if a table/column exists before 
    # creating/adding it. This prevents crashes if the DB is in an out-of-sync state.
    # 
    # Example helper for table check:
    # conn = op.get_bind()
    # inspector = sa.inspect(conn)
    # tables = inspector.get_table_names()
    # if 'my_table' not in tables:
    #     op.create_table(...)
    # =========================================================================
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_card_mastery', sa.Column('is_ignored', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_card_mastery', 'is_ignored')
    # ### end Alembic commands ###
