"""Add is_archived to QuizAttempt

Revision ID: 1d6d0966daae
Revises: 497aee096b3b
Create Date: 2026-05-08 23:06:04.480818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6d0966daae'
down_revision: Union[str, Sequence[str], None] = '497aee096b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_attempts', 'is_archived')
    # ### end Alembic commands ###
