"""add advanced bot settings

Revision ID: 31006bdc4339
Revises: 7f942e9fb831
Create Date: 2026-05-30 20:08:57.439700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31006bdc4339'
down_revision: Union[str, Sequence[str], None] = '7f942e9fb831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_telegram_configs', sa.Column('streak_guard_enabled', sa.Boolean(), nullable=True))
    op.add_column('user_telegram_configs', sa.Column('weekly_summary_enabled', sa.Boolean(), nullable=True))
    op.add_column('user_telegram_configs', sa.Column('inactivity_alert_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_telegram_configs', 'inactivity_alert_enabled')
    op.drop_column('user_telegram_configs', 'weekly_summary_enabled')
    op.drop_column('user_telegram_configs', 'streak_guard_enabled')
    # ### end Alembic commands ###
