"""Add UserTelegramConfig and PushSubscription models

Revision ID: 7f942e9fb831
Revises: 8e1f3c639daa
Create Date: 2026-05-30 14:52:50.994252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f942e9fb831'
down_revision: Union[str, Sequence[str], None] = '8e1f3c639daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
