"""Add UserTelegramConfig and PushSubscription models

Revision ID: 7f942e9fb831
Revises: 8e1f3c639daa
Create Date: 2026-05-30 14:52:50.994252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f942e9fb831'
down_revision: Union[str, Sequence[str], None] = '8e1f3c639daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=512), nullable=True),
    sa.Column('p256dh', sa.String(length=255), nullable=True),
    sa.Column('auth', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_subscriptions_endpoint'), 'push_subscriptions', ['endpoint'], unique=True)
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)

    op.create_table('user_telegram_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=100), nullable=True),
    sa.Column('connect_token', sa.String(length=50), nullable=True),
    sa.Column('reminder_time', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_telegram_configs_connect_token'), 'user_telegram_configs', ['connect_token'], unique=True)
    op.create_index(op.f('ix_user_telegram_configs_id'), 'user_telegram_configs', ['id'], unique=False)
    op.create_index(op.f('ix_user_telegram_configs_telegram_chat_id'), 'user_telegram_configs', ['telegram_chat_id'], unique=False)
    op.create_index(op.f('ix_user_telegram_configs_user_id'), 'user_telegram_configs', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telegram_configs_user_id'), table_name='user_telegram_configs')
    op.drop_index(op.f('ix_user_telegram_configs_telegram_chat_id'), table_name='user_telegram_configs')
    op.drop_index(op.f('ix_user_telegram_configs_id'), table_name='user_telegram_configs')
    op.drop_index(op.f('ix_user_telegram_configs_connect_token'), table_name='user_telegram_configs')
    op.drop_table('user_telegram_configs')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_endpoint'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
