"""add_user_daily_activity

Revision ID: 814a9927281a
Revises: 9282347952f1
Create Date: 2026-05-21 21:23:35.811373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '814a9927281a'
down_revision: Union[str, Sequence[str], None] = '9282347952f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_daily_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_daily_activities_activity_date'), 'user_daily_activities', ['activity_date'], unique=False)
    op.create_index(op.f('ix_user_daily_activities_user_id'), 'user_daily_activities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_daily_activities_user_id'), table_name='user_daily_activities')
    op.drop_index(op.f('ix_user_daily_activities_activity_date'), table_name='user_daily_activities')
    op.drop_table('user_daily_activities')
    # ### end Alembic commands ###
