"""Add daily_new_card_target

Revision ID: 8e1f3c639daa
Revises: 5a336d813283
Create Date: 2026-05-30 13:37:45.912556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1f3c639daa'
down_revision: Union[str, Sequence[str], None] = '5a336d813283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_global_goals', sa.Column('daily_new_card_target', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_global_goals', 'daily_new_card_target')
    # ### end Alembic commands ###
