"""Add cover_image to quiz

Revision ID: 9282347952f1
Revises: 7b5ca499bf39
Create Date: 2026-05-12 22:32:10.221715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9282347952f1'
down_revision: Union[str, Sequence[str], None] = '7b5ca499bf39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('cover_image', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'cover_image')
    # ### end Alembic commands ###
