"""Initial migration

Revision ID: c04cfa2aa29e
Revises: 
Create Date: 2026-05-26 10:00:10.874663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04cfa2aa29e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('badges',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('criteria_type', sa.String(length=50), nullable=True),
    sa.Column('criteria_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('sso_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('server_url', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=100), nullable=True),
    sa.Column('client_secret', sa.String(length=255), nullable=True),
    sa.Column('redirect_uri', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sso_settings_id'), 'sso_settings', ['id'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('user_daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('questions_attempted', sa.Integer(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('total_time_seconds', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_daily_stats_user_id'), 'user_daily_stats', ['user_id'], unique=False)
    op.create_table('user_gamification',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('streak_count', sa.Integer(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('badges', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sso_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_sso_id'), 'users', ['sso_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('flashcard_decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=512), nullable=True),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('practice_settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_decks_category_id'), 'flashcard_decks', ['category_id'], unique=False)
    op.create_index(op.f('ix_flashcard_decks_id'), 'flashcard_decks', ['id'], unique=False)
    op.create_index(op.f('ix_flashcard_decks_title'), 'flashcard_decks', ['title'], unique=False)
    op.create_table('user_daily_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_daily_activities_activity_date'), 'user_daily_activities', ['activity_date'], unique=False)
    op.create_index(op.f('ix_user_daily_activities_user_id'), 'user_daily_activities', ['user_id'], unique=False)
    op.create_table('deck_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['flashcard_decks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_attempts_id'), 'deck_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_deck_attempts_quiz_id'), 'deck_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_deck_attempts_user_id'), 'deck_attempts', ['user_id'], unique=False)
    op.create_table('deck_collaborators',
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['flashcard_decks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('quiz_id', 'user_id')
    )
    op.create_table('deck_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('room_code', sa.String(length=20), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['flashcard_decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_rooms_host_id'), 'deck_rooms', ['host_id'], unique=False)
    op.create_index(op.f('ix_deck_rooms_id'), 'deck_rooms', ['id'], unique=False)
    op.create_index(op.f('ix_deck_rooms_quiz_id'), 'deck_rooms', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_deck_rooms_room_code'), 'deck_rooms', ['room_code'], unique=True)
    op.create_table('deck_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('current_index', sa.Integer(), nullable=True),
    sa.Column('state_json', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['flashcard_decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_sessions_id'), 'deck_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_deck_sessions_quiz_id'), 'deck_sessions', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_deck_sessions_user_id'), 'deck_sessions', ['user_id'], unique=False)
    op.create_table('deck_tags',
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['flashcard_decks.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('quiz_id', 'tag_id')
    )
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('audio', sa.String(length=512), nullable=True),
    sa.Column('question_type', sa.String(length=50), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('others', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['flashcard_decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_id'), 'flashcards', ['id'], unique=False)
    op.create_index(op.f('ix_flashcards_quiz_id'), 'flashcards', ['quiz_id'], unique=False)
    op.create_table('user_deck_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('daily_target', sa.Integer(), nullable=True),
    sa.Column('streak_count', sa.Integer(), nullable=True),
    sa.Column('last_completed_date', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['flashcard_decks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_deck_goals_id'), 'user_deck_goals', ['id'], unique=False)
    op.create_index(op.f('ix_user_deck_goals_quiz_id'), 'user_deck_goals', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_user_deck_goals_user_id'), 'user_deck_goals', ['user_id'], unique=False)
    op.create_table('user_deck_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcard_decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_deck_settings_deck_id'), 'user_deck_settings', ['deck_id'], unique=False)
    op.create_index(op.f('ix_user_deck_settings_id'), 'user_deck_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_deck_settings_user_id'), 'user_deck_settings', ['user_id'], unique=False)
    op.create_table('card_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('active_time', sa.Float(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['deck_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['flashcards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_answers_attempt_id'), 'card_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_card_answers_id'), 'card_answers', ['id'], unique=False)
    op.create_index(op.f('ix_card_answers_question_id'), 'card_answers', ['question_id'], unique=False)
    op.create_table('deck_room_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['deck_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_room_chats_id'), 'deck_room_chats', ['id'], unique=False)
    op.create_index(op.f('ix_deck_room_chats_room_id'), 'deck_room_chats', ['room_id'], unique=False)
    op.create_index(op.f('ix_deck_room_chats_user_id'), 'deck_room_chats', ['user_id'], unique=False)
    op.create_table('deck_room_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total_answered', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['deck_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_room_participants_id'), 'deck_room_participants', ['id'], unique=False)
    op.create_index(op.f('ix_deck_room_participants_room_id'), 'deck_room_participants', ['room_id'], unique=False)
    op.create_index(op.f('ix_deck_room_participants_user_id'), 'deck_room_participants', ['user_id'], unique=False)
    op.create_table('user_card_mastery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('box_level', sa.Integer(), nullable=True),
    sa.Column('consecutive_correct', sa.Integer(), nullable=True),
    sa.Column('last_answered', sa.DateTime(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('due', sa.DateTime(), nullable=True),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['flashcards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_card_mastery_due'), 'user_card_mastery', ['due'], unique=False)
    op.create_index(op.f('ix_user_card_mastery_id'), 'user_card_mastery', ['id'], unique=False)
    op.create_index(op.f('ix_user_card_mastery_question_id'), 'user_card_mastery', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_card_mastery_user_id'), 'user_card_mastery', ['user_id'], unique=False)
    op.create_table('user_card_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['flashcards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_card_notes_id'), 'user_card_notes', ['id'], unique=False)
    op.create_index(op.f('ix_user_card_notes_question_id'), 'user_card_notes', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_card_notes_user_id'), 'user_card_notes', ['user_id'], unique=False)
    op.create_table('user_daily_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('count_done', sa.Integer(), nullable=True),
    sa.Column('is_target_met', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['user_deck_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_daily_progress_date'), 'user_daily_progress', ['date'], unique=False)
    op.create_index(op.f('ix_user_daily_progress_goal_id'), 'user_daily_progress', ['goal_id'], unique=False)
    op.create_index(op.f('ix_user_daily_progress_id'), 'user_daily_progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_daily_progress_id'), table_name='user_daily_progress')
    op.drop_index(op.f('ix_user_daily_progress_goal_id'), table_name='user_daily_progress')
    op.drop_index(op.f('ix_user_daily_progress_date'), table_name='user_daily_progress')
    op.drop_table('user_daily_progress')
    op.drop_index(op.f('ix_user_card_notes_user_id'), table_name='user_card_notes')
    op.drop_index(op.f('ix_user_card_notes_question_id'), table_name='user_card_notes')
    op.drop_index(op.f('ix_user_card_notes_id'), table_name='user_card_notes')
    op.drop_table('user_card_notes')
    op.drop_index(op.f('ix_user_card_mastery_user_id'), table_name='user_card_mastery')
    op.drop_index(op.f('ix_user_card_mastery_question_id'), table_name='user_card_mastery')
    op.drop_index(op.f('ix_user_card_mastery_id'), table_name='user_card_mastery')
    op.drop_index(op.f('ix_user_card_mastery_due'), table_name='user_card_mastery')
    op.drop_table('user_card_mastery')
    op.drop_index(op.f('ix_deck_room_participants_user_id'), table_name='deck_room_participants')
    op.drop_index(op.f('ix_deck_room_participants_room_id'), table_name='deck_room_participants')
    op.drop_index(op.f('ix_deck_room_participants_id'), table_name='deck_room_participants')
    op.drop_table('deck_room_participants')
    op.drop_index(op.f('ix_deck_room_chats_user_id'), table_name='deck_room_chats')
    op.drop_index(op.f('ix_deck_room_chats_room_id'), table_name='deck_room_chats')
    op.drop_index(op.f('ix_deck_room_chats_id'), table_name='deck_room_chats')
    op.drop_table('deck_room_chats')
    op.drop_index(op.f('ix_card_answers_question_id'), table_name='card_answers')
    op.drop_index(op.f('ix_card_answers_id'), table_name='card_answers')
    op.drop_index(op.f('ix_card_answers_attempt_id'), table_name='card_answers')
    op.drop_table('card_answers')
    op.drop_index(op.f('ix_user_deck_settings_user_id'), table_name='user_deck_settings')
    op.drop_index(op.f('ix_user_deck_settings_id'), table_name='user_deck_settings')
    op.drop_index(op.f('ix_user_deck_settings_deck_id'), table_name='user_deck_settings')
    op.drop_table('user_deck_settings')
    op.drop_index(op.f('ix_user_deck_goals_user_id'), table_name='user_deck_goals')
    op.drop_index(op.f('ix_user_deck_goals_quiz_id'), table_name='user_deck_goals')
    op.drop_index(op.f('ix_user_deck_goals_id'), table_name='user_deck_goals')
    op.drop_table('user_deck_goals')
    op.drop_index(op.f('ix_flashcards_quiz_id'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_table('deck_tags')
    op.drop_index(op.f('ix_deck_sessions_user_id'), table_name='deck_sessions')
    op.drop_index(op.f('ix_deck_sessions_quiz_id'), table_name='deck_sessions')
    op.drop_index(op.f('ix_deck_sessions_id'), table_name='deck_sessions')
    op.drop_table('deck_sessions')
    op.drop_index(op.f('ix_deck_rooms_room_code'), table_name='deck_rooms')
    op.drop_index(op.f('ix_deck_rooms_quiz_id'), table_name='deck_rooms')
    op.drop_index(op.f('ix_deck_rooms_id'), table_name='deck_rooms')
    op.drop_index(op.f('ix_deck_rooms_host_id'), table_name='deck_rooms')
    op.drop_table('deck_rooms')
    op.drop_table('deck_collaborators')
    op.drop_index(op.f('ix_deck_attempts_user_id'), table_name='deck_attempts')
    op.drop_index(op.f('ix_deck_attempts_quiz_id'), table_name='deck_attempts')
    op.drop_index(op.f('ix_deck_attempts_id'), table_name='deck_attempts')
    op.drop_table('deck_attempts')
    op.drop_index(op.f('ix_user_daily_activities_user_id'), table_name='user_daily_activities')
    op.drop_index(op.f('ix_user_daily_activities_activity_date'), table_name='user_daily_activities')
    op.drop_table('user_daily_activities')
    op.drop_index(op.f('ix_flashcard_decks_title'), table_name='flashcard_decks')
    op.drop_index(op.f('ix_flashcard_decks_id'), table_name='flashcard_decks')
    op.drop_index(op.f('ix_flashcard_decks_category_id'), table_name='flashcard_decks')
    op.drop_table('flashcard_decks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_sso_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_gamification')
    op.drop_index(op.f('ix_user_daily_stats_user_id'), table_name='user_daily_stats')
    op.drop_table('user_daily_stats')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_sso_settings_id'), table_name='sso_settings')
    op.drop_table('sso_settings')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_table('badges')
    op.drop_table('admin_logs')
    # ### end Alembic commands ###
