"""optimize_db_indexes

Revision ID: c563cc516aaa
Revises: 814a9927281a
Create Date: 2026-05-21 21:27:14.830530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c563cc516aaa'
down_revision: Union[str, Sequence[str], None] = '814a9927281a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_options_question_id'), 'options', ['question_id'], unique=False)
    op.create_index(op.f('ix_questions_quiz_id'), 'questions', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_index(op.f('ix_quiz_room_participants_room_id'), 'quiz_room_participants', ['room_id'], unique=False)
    op.create_index(op.f('ix_quiz_room_participants_user_id'), 'quiz_room_participants', ['user_id'], unique=False)
    op.create_index(op.f('ix_quiz_rooms_host_id'), 'quiz_rooms', ['host_id'], unique=False)
    op.create_index(op.f('ix_quiz_rooms_quiz_id'), 'quiz_rooms', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_quiz_id'), 'quiz_sessions', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quizzes_category_id'), 'quizzes', ['category_id'], unique=False)
    op.create_index(op.f('ix_user_answers_attempt_id'), 'user_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_user_answers_question_id'), 'user_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_question_notes_question_id'), 'user_question_notes', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_question_notes_user_id'), 'user_question_notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_question_notes_user_id'), table_name='user_question_notes')
    op.drop_index(op.f('ix_user_question_notes_question_id'), table_name='user_question_notes')
    op.drop_index(op.f('ix_user_answers_question_id'), table_name='user_answers')
    op.drop_index(op.f('ix_user_answers_attempt_id'), table_name='user_answers')
    op.drop_index(op.f('ix_quizzes_category_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quiz_sessions_quiz_id'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_rooms_quiz_id'), table_name='quiz_rooms')
    op.drop_index(op.f('ix_quiz_rooms_host_id'), table_name='quiz_rooms')
    op.drop_index(op.f('ix_quiz_room_participants_user_id'), table_name='quiz_room_participants')
    op.drop_index(op.f('ix_quiz_room_participants_room_id'), table_name='quiz_room_participants')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_questions_quiz_id'), table_name='questions')
    op.drop_index(op.f('ix_options_question_id'), table_name='options')
    # ### end Alembic commands ###
