"""Add XPTransaction table

Revision ID: d53f6d21cd04
Revises: 31006bdc4339
Create Date: 2026-05-31 14:16:07.329883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd53f6d21cd04'
down_revision: Union[str, Sequence[str], None] = '31006bdc4339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # =========================================================================
    # ECOSYSTEM MIGRATION GUIDELINE:
    # Always write IDEMPOTENT migrations. Check if a table/column exists before 
    # creating/adding it. This prevents crashes if the DB is in an out-of-sync state.
    # 
    # Example helper for table check:
    # conn = op.get_bind()
    # inspector = sa.inspect(conn)
    # tables = inspector.get_table_names()
    # if 'my_table' not in tables:
    #     op.create_table(...)
    # =========================================================================
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xp_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_transactions_created_at'), 'xp_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_xp_transactions_user_id'), 'xp_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xp_transactions_user_id'), table_name='xp_transactions')
    op.drop_index(op.f('ix_xp_transactions_created_at'), table_name='xp_transactions')
    op.drop_table('xp_transactions')
    # ### end Alembic commands ###
