"""Add QuizRoom and QuizRoomParticipant

Revision ID: defd8a008a32
Revises: f170723a62b1
Create Date: 2026-05-11 22:09:00.376752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'defd8a008a32'
down_revision: Union[str, Sequence[str], None] = 'f170723a62b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()

    # Create quiz_rooms if not exists
    if 'quiz_rooms' not in existing_tables:
        op.create_table('quiz_rooms',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('quiz_id', sa.Integer(), nullable=True),
            sa.Column('room_code', sa.String(length=20), nullable=True),
            sa.Column('host_id', sa.Integer(), nullable=True),
            sa.Column('status', sa.String(length=50), nullable=True),
            sa.Column('settings', sa.JSON(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('started_at', sa.DateTime(), nullable=True),
            sa.Column('finished_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
            sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_quiz_rooms_id'), 'quiz_rooms', ['id'], unique=False)
        op.create_index(op.f('ix_quiz_rooms_room_code'), 'quiz_rooms', ['room_code'], unique=True)

    # Create quiz_room_participants if not exists
    if 'quiz_room_participants' not in existing_tables:
        op.create_table('quiz_room_participants',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('room_id', sa.Integer(), nullable=True),
            sa.Column('user_id', sa.Integer(), nullable=True),
            sa.Column('is_ready', sa.Boolean(), nullable=True),
            sa.Column('score', sa.Integer(), nullable=True),
            sa.Column('total_answered', sa.Integer(), nullable=True),
            sa.Column('joined_at', sa.DateTime(), nullable=True),
            sa.Column('last_active', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['room_id'], ['quiz_rooms.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_quiz_room_participants_id'), 'quiz_room_participants', ['id'], unique=False)

    # Check for index on quiz_sessions separately
    indexes = [idx['name'] for idx in inspector.get_indexes('quiz_sessions')]
    if 'ix_quiz_sessions_user_id' not in indexes:
        op.create_index(op.f('ix_quiz_sessions_user_id'), 'quiz_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_sessions_user_id'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_room_participants_id'), table_name='quiz_room_participants')
    op.drop_table('quiz_room_participants')
    op.drop_index(op.f('ix_quiz_rooms_room_code'), table_name='quiz_rooms')
    op.drop_index(op.f('ix_quiz_rooms_id'), table_name='quiz_rooms')
    op.drop_table('quiz_rooms')
    # ### end Alembic commands ###
