"""add quizroomchat table

Revision ID: ec0334756c58
Revises: 0b58b128aa3c
Create Date: 2026-05-23 20:51:48.411437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec0334756c58'
down_revision: Union[str, Sequence[str], None] = '0b58b128aa3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_room_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['quiz_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_room_chats_id'), 'quiz_room_chats', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_room_chats_room_id'), 'quiz_room_chats', ['room_id'], unique=False)
    op.create_index(op.f('ix_quiz_room_chats_user_id'), 'quiz_room_chats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_room_chats_user_id'), table_name='quiz_room_chats')
    op.drop_index(op.f('ix_quiz_room_chats_room_id'), table_name='quiz_room_chats')
    op.drop_index(op.f('ix_quiz_room_chats_id'), table_name='quiz_room_chats')
    op.drop_table('quiz_room_chats')
    # ### end Alembic commands ###
