"""add_practice_settings_and_user_deck_settings

Revision ID: f2a7650d5b9e
Revises: 0469dac9b44b
Create Date: 2026-05-25 20:18:13.881309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a7650d5b9e'
down_revision: Union[str, Sequence[str], None] = '0469dac9b44b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_deck_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcard_decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_deck_settings_deck_id'), 'user_deck_settings', ['deck_id'], unique=False)
    op.create_index(op.f('ix_user_deck_settings_id'), 'user_deck_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_deck_settings_user_id'), 'user_deck_settings', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_answers_attempt_id'), table_name='card_answers')
    op.drop_index(op.f('ix_user_answers_id'), table_name='card_answers')
    op.drop_index(op.f('ix_user_answers_question_id'), table_name='card_answers')
    op.create_index(op.f('ix_card_answers_attempt_id'), 'card_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_card_answers_id'), 'card_answers', ['id'], unique=False)
    op.create_index(op.f('ix_card_answers_question_id'), 'card_answers', ['question_id'], unique=False)
    op.drop_index(op.f('ix_quiz_attempts_id'), table_name='deck_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='deck_attempts')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='deck_attempts')
    op.create_index(op.f('ix_deck_attempts_id'), 'deck_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_deck_attempts_quiz_id'), 'deck_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_deck_attempts_user_id'), 'deck_attempts', ['user_id'], unique=False)
    op.drop_index(op.f('ix_quiz_room_chats_id'), table_name='deck_room_chats')
    op.drop_index(op.f('ix_quiz_room_chats_room_id'), table_name='deck_room_chats')
    op.drop_index(op.f('ix_quiz_room_chats_user_id'), table_name='deck_room_chats')
    op.create_index(op.f('ix_deck_room_chats_id'), 'deck_room_chats', ['id'], unique=False)
    op.create_index(op.f('ix_deck_room_chats_room_id'), 'deck_room_chats', ['room_id'], unique=False)
    op.create_index(op.f('ix_deck_room_chats_user_id'), 'deck_room_chats', ['user_id'], unique=False)
    op.drop_index(op.f('ix_quiz_room_participants_id'), table_name='deck_room_participants')
    op.drop_index(op.f('ix_quiz_room_participants_room_id'), table_name='deck_room_participants')
    op.drop_index(op.f('ix_quiz_room_participants_user_id'), table_name='deck_room_participants')
    op.create_index(op.f('ix_deck_room_participants_id'), 'deck_room_participants', ['id'], unique=False)
    op.create_index(op.f('ix_deck_room_participants_room_id'), 'deck_room_participants', ['room_id'], unique=False)
    op.create_index(op.f('ix_deck_room_participants_user_id'), 'deck_room_participants', ['user_id'], unique=False)
    op.drop_index(op.f('ix_quiz_rooms_host_id'), table_name='deck_rooms')
    op.drop_index(op.f('ix_quiz_rooms_id'), table_name='deck_rooms')
    op.drop_index(op.f('ix_quiz_rooms_quiz_id'), table_name='deck_rooms')
    op.drop_index(op.f('ix_quiz_rooms_room_code'), table_name='deck_rooms')
    op.create_index(op.f('ix_deck_rooms_host_id'), 'deck_rooms', ['host_id'], unique=False)
    op.create_index(op.f('ix_deck_rooms_id'), 'deck_rooms', ['id'], unique=False)
    op.create_index(op.f('ix_deck_rooms_quiz_id'), 'deck_rooms', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_deck_rooms_room_code'), 'deck_rooms', ['room_code'], unique=True)
    op.drop_index(op.f('ix_quiz_sessions_id'), table_name='deck_sessions')
    op.drop_index(op.f('ix_quiz_sessions_quiz_id'), table_name='deck_sessions')
    op.drop_index(op.f('ix_quiz_sessions_user_id'), table_name='deck_sessions')
    op.create_index(op.f('ix_deck_sessions_id'), 'deck_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_deck_sessions_quiz_id'), 'deck_sessions', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_deck_sessions_user_id'), 'deck_sessions', ['user_id'], unique=False)
    op.add_column('flashcard_decks', sa.Column('practice_settings', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_quizzes_category_id'), table_name='flashcard_decks')
    op.drop_index(op.f('ix_quizzes_id'), table_name='flashcard_decks')
    op.drop_index(op.f('ix_quizzes_title'), table_name='flashcard_decks')
    op.create_index(op.f('ix_flashcard_decks_category_id'), 'flashcard_decks', ['category_id'], unique=False)
    op.create_index(op.f('ix_flashcard_decks_id'), 'flashcard_decks', ['id'], unique=False)
    op.create_index(op.f('ix_flashcard_decks_title'), 'flashcard_decks', ['title'], unique=False)
    op.drop_index(op.f('ix_questions_id'), table_name='flashcards')
    op.drop_index(op.f('ix_questions_quiz_id'), table_name='flashcards')
    op.create_index(op.f('ix_flashcards_id'), 'flashcards', ['id'], unique=False)
    op.create_index(op.f('ix_flashcards_quiz_id'), 'flashcards', ['quiz_id'], unique=False)
    op.drop_index(op.f('ix_user_question_mastery_due'), table_name='user_card_mastery')
    op.drop_index(op.f('ix_user_question_mastery_id'), table_name='user_card_mastery')
    op.drop_index(op.f('ix_user_question_mastery_question_id'), table_name='user_card_mastery')
    op.drop_index(op.f('ix_user_question_mastery_user_id'), table_name='user_card_mastery')
    op.create_index(op.f('ix_user_card_mastery_id'), 'user_card_mastery', ['id'], unique=False)
    op.create_index(op.f('ix_user_card_mastery_question_id'), 'user_card_mastery', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_card_mastery_user_id'), 'user_card_mastery', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_question_notes_id'), table_name='user_card_notes')
    op.drop_index(op.f('ix_user_question_notes_question_id'), table_name='user_card_notes')
    op.drop_index(op.f('ix_user_question_notes_user_id'), table_name='user_card_notes')
    op.create_index(op.f('ix_user_card_notes_id'), 'user_card_notes', ['id'], unique=False)
    op.create_index(op.f('ix_user_card_notes_question_id'), 'user_card_notes', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_card_notes_user_id'), 'user_card_notes', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_quiz_goals_id'), table_name='user_deck_goals')
    op.drop_index(op.f('ix_user_quiz_goals_quiz_id'), table_name='user_deck_goals')
    op.drop_index(op.f('ix_user_quiz_goals_user_id'), table_name='user_deck_goals')
    op.create_index(op.f('ix_user_deck_goals_id'), 'user_deck_goals', ['id'], unique=False)
    op.create_index(op.f('ix_user_deck_goals_quiz_id'), 'user_deck_goals', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_user_deck_goals_user_id'), 'user_deck_goals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_deck_goals_user_id'), table_name='user_deck_goals')
    op.drop_index(op.f('ix_user_deck_goals_quiz_id'), table_name='user_deck_goals')
    op.drop_index(op.f('ix_user_deck_goals_id'), table_name='user_deck_goals')
    op.create_index(op.f('ix_user_quiz_goals_user_id'), 'user_deck_goals', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_quiz_goals_quiz_id'), 'user_deck_goals', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_user_quiz_goals_id'), 'user_deck_goals', ['id'], unique=False)
    op.drop_index(op.f('ix_user_card_notes_user_id'), table_name='user_card_notes')
    op.drop_index(op.f('ix_user_card_notes_question_id'), table_name='user_card_notes')
    op.drop_index(op.f('ix_user_card_notes_id'), table_name='user_card_notes')
    op.create_index(op.f('ix_user_question_notes_user_id'), 'user_card_notes', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_question_notes_question_id'), 'user_card_notes', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_question_notes_id'), 'user_card_notes', ['id'], unique=False)
    op.drop_index(op.f('ix_user_card_mastery_user_id'), table_name='user_card_mastery')
    op.drop_index(op.f('ix_user_card_mastery_question_id'), table_name='user_card_mastery')
    op.drop_index(op.f('ix_user_card_mastery_id'), table_name='user_card_mastery')
    op.create_index(op.f('ix_user_question_mastery_user_id'), 'user_card_mastery', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_question_mastery_question_id'), 'user_card_mastery', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_question_mastery_id'), 'user_card_mastery', ['id'], unique=False)
    op.create_index(op.f('ix_user_question_mastery_due'), 'user_card_mastery', ['due'], unique=False)
    op.drop_index(op.f('ix_flashcards_quiz_id'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_id'), table_name='flashcards')
    op.create_index(op.f('ix_questions_quiz_id'), 'flashcards', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'flashcards', ['id'], unique=False)
    op.drop_index(op.f('ix_flashcard_decks_title'), table_name='flashcard_decks')
    op.drop_index(op.f('ix_flashcard_decks_id'), table_name='flashcard_decks')
    op.drop_index(op.f('ix_flashcard_decks_category_id'), table_name='flashcard_decks')
    op.create_index(op.f('ix_quizzes_title'), 'flashcard_decks', ['title'], unique=False)
    op.create_index(op.f('ix_quizzes_id'), 'flashcard_decks', ['id'], unique=False)
    op.create_index(op.f('ix_quizzes_category_id'), 'flashcard_decks', ['category_id'], unique=False)
    op.drop_column('flashcard_decks', 'practice_settings')
    op.drop_index(op.f('ix_deck_sessions_user_id'), table_name='deck_sessions')
    op.drop_index(op.f('ix_deck_sessions_quiz_id'), table_name='deck_sessions')
    op.drop_index(op.f('ix_deck_sessions_id'), table_name='deck_sessions')
    op.create_index(op.f('ix_quiz_sessions_user_id'), 'deck_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_quiz_id'), 'deck_sessions', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_id'), 'deck_sessions', ['id'], unique=False)
    op.drop_index(op.f('ix_deck_rooms_room_code'), table_name='deck_rooms')
    op.drop_index(op.f('ix_deck_rooms_quiz_id'), table_name='deck_rooms')
    op.drop_index(op.f('ix_deck_rooms_id'), table_name='deck_rooms')
    op.drop_index(op.f('ix_deck_rooms_host_id'), table_name='deck_rooms')
    op.create_index(op.f('ix_quiz_rooms_room_code'), 'deck_rooms', ['room_code'], unique=1)
    op.create_index(op.f('ix_quiz_rooms_quiz_id'), 'deck_rooms', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_rooms_id'), 'deck_rooms', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_rooms_host_id'), 'deck_rooms', ['host_id'], unique=False)
    op.drop_index(op.f('ix_deck_room_participants_user_id'), table_name='deck_room_participants')
    op.drop_index(op.f('ix_deck_room_participants_room_id'), table_name='deck_room_participants')
    op.drop_index(op.f('ix_deck_room_participants_id'), table_name='deck_room_participants')
    op.create_index(op.f('ix_quiz_room_participants_user_id'), 'deck_room_participants', ['user_id'], unique=False)
    op.create_index(op.f('ix_quiz_room_participants_room_id'), 'deck_room_participants', ['room_id'], unique=False)
    op.create_index(op.f('ix_quiz_room_participants_id'), 'deck_room_participants', ['id'], unique=False)
    op.drop_index(op.f('ix_deck_room_chats_user_id'), table_name='deck_room_chats')
    op.drop_index(op.f('ix_deck_room_chats_room_id'), table_name='deck_room_chats')
    op.drop_index(op.f('ix_deck_room_chats_id'), table_name='deck_room_chats')
    op.create_index(op.f('ix_quiz_room_chats_user_id'), 'deck_room_chats', ['user_id'], unique=False)
    op.create_index(op.f('ix_quiz_room_chats_room_id'), 'deck_room_chats', ['room_id'], unique=False)
    op.create_index(op.f('ix_quiz_room_chats_id'), 'deck_room_chats', ['id'], unique=False)
    op.drop_index(op.f('ix_deck_attempts_user_id'), table_name='deck_attempts')
    op.drop_index(op.f('ix_deck_attempts_quiz_id'), table_name='deck_attempts')
    op.drop_index(op.f('ix_deck_attempts_id'), table_name='deck_attempts')
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'deck_attempts', ['user_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'deck_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_id'), 'deck_attempts', ['id'], unique=False)
    op.drop_index(op.f('ix_card_answers_question_id'), table_name='card_answers')
    op.drop_index(op.f('ix_card_answers_id'), table_name='card_answers')
    op.drop_index(op.f('ix_card_answers_attempt_id'), table_name='card_answers')
    op.create_index(op.f('ix_user_answers_question_id'), 'card_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_answers_id'), 'card_answers', ['id'], unique=False)
    op.create_index(op.f('ix_user_answers_attempt_id'), 'card_answers', ['attempt_id'], unique=False)
    op.drop_index(op.f('ix_user_deck_settings_user_id'), table_name='user_deck_settings')
    op.drop_index(op.f('ix_user_deck_settings_id'), table_name='user_deck_settings')
    op.drop_index(op.f('ix_user_deck_settings_deck_id'), table_name='user_deck_settings')
    op.drop_table('user_deck_settings')
    # ### end Alembic commands ###
